CREATE DATABASE atividade_adbd;

USE atividade_adbd;

DROP TABLE IF EXISTS CLIENTE, MUNICIPIO, UF, TELEFONE, TIPO_PAGTO, VENDAS, DOCUMENTO, PRODUTO, VENDA, ITEM_VENDA, ENTRADA, SAIDA, LOTE;

CREATE TABLE CLIENTE (
	id INT AUTO_INCREMENT,
    nome VARCHAR(50),
    logradouro VARCHAR(30),
    numero VARCHAR(6),
    bairro VARCHAR(20),
    MUNICIPIO_id INT,
    MUNICIPIO_UF_id INT,
    PRIMARY KEY(id),
    CONSTRAINT CLIENTE_MUNICIPIO_FK FOREIGN KEY (MUNICIPIO_id) REFERENCES MUNICIPIO (id),
    CONSTRAINT CLIENTE_MUNICIPIO_UF_FK FOREIGN KEY (MUNICIPIO_UF_id) REFERENCES MUNICIPIO(UF_id)
);

CREATE TABLE MUNICIPIO (
	id INT AUTO_INCREMENT,
    nome VARCHAR(30),
    UF_id INT,
    PRIMARY KEY(id),
    CONSTRAINT MUNICIPIO_UF_FK FOREIGN KEY (UF_id) REFERENCES UF(id)
);

CREATE TABLE UF (
	id INT AUTO_INCREMENT,
    nome VARCHAR(20),
    sigla VARCHAR(2),
    PRIMARY KEY (id)
);

CREATE TABLE TELEFONE (
	id INT AUTO_INCREMENT,
    numero VARCHAR(15),
    CLIENTE_id INT,
    CLIENTE_MUNICIPIO_id INT,
    CLIENTE_MUNICIPIO_UF_id INT,
    PRIMARY KEY(id),
    CONSTRAINT TELEFONE_CLIENTE_FK FOREIGN KEY (CLIENTE_id) REFERENCES CLIENTE (id),
    CONSTRAINT TELEFONE_CLIENTE_MUNICIPIO_FK FOREIGN KEY (CLIENTE_MUNICIPIO_id) REFERENCES CLIENTE (MUNICIPIO_id),
    CONSTRAINT TELEFONE_CLIENTE_MUNICIPIO_UF_FK FOREIGN KEY (CLIENTE_MUNICIPIO_UF_id) REFERENCES CLIENTE(MUNICIPIO_UF_id)
);

CREATE TABLE TIPO_PAGTO(
	id INT AUTO_INCREMENT,
    tipo_pagto VARCHAR(20),
    PRIMARY KEY(id)
);

CREATE TABLE VENDA(
	id INT AUTO_INCREMENT,
    dt_venda DATE,
    TIPO_PAGTO_id INT,
    CLIENTE_id INT,
    PRIMARY KEY(id),
    CONSTRAINT VENDA_TIPO_PAGTO_FK FOREIGN KEY (TIPO_PAGTO_id) REFERENCES TIPO_PAGTO(id),
	CONSTRAINT VENDA_CLIENTE_FK FOREIGN KEY (CLIENTE_id) REFERENCES CLIENTE(id)
);

CREATE TABLE DOCUMENTO (
	id INT AUTO_INCREMENT,
    vr_documento DECIMAL,
    dt_venc DATE,
    VENDA_id INT,
    VENDA_TIPO_PAGTO_id INT,
    CLIENTE_id INT,
    PRIMARY KEY(id),
    CONSTRAINT DOCUMENTO_VENDA_FK FOREIGN KEY (VENDA_id) REFERENCES VENDA(id),
    CONSTRAINT DOCUMENTO_VENDA_TIPO_PAGTO_FK FOREIGN KEY (VENDA_TIPO_PAGTO_id) REFERENCES VENDA(TIPO_PAGTO_id),
    CONSTRAINT DOCUMENTO_CLIENTE_FK FOREIGN KEY (CLIENTE_id) REFERENCES CLIENTE(id)
);

CREATE TABLE PRODUTO(
	id INT AUTO_INCREMENT,
    descricao VARCHAR(30),
    quant DECIMAL(9,3),
    valor DECIMAL(5,2),
    qt_minima DECIMAL(9,3),
    perecivel BOOLEAN,
    PRIMARY KEY (id)
);

CREATE TABLE ITEM_VENDA(
	VENDA_id INT,
    PRODUTO_id INT,
    qt_item DECIMAL(9,3),
    vr_item DECIMAL(9,3),
    CONSTRAINT ITEM_VENDA_VENDA_FK FOREIGN KEY (VENDA_id) REFERENCES VENDA(id),
    CONSTRAINT ITEM_VENDA_PRODUTO_FK FOREIGN KEY (PRODUTO_id) REFERENCES PRODUTO(id)
);

CREATE TABLE ENTRADA(
	id INT AUTO_INCREMENT,
    dt_entrada DATE,
	qt_entrada DECIMAL(9,3),
    PRODUTO_id INT,
    PRIMARY KEY (id),
    CONSTRAINT ENTRADA_PRODUTO_FK FOREIGN KEY (PRODUTO_id) REFERENCES PRODUTO(id)
);

CREATE TABLE SAIDA(
	id INT AUTO_INCREMENT,
    dt_saida DATE,
	qt_entrada DECIMAL(9,3),
    SAIDAcol VARCHAR(45),
    PRODUTO_id INT,
    PRIMARY KEY (id),
    CONSTRAINT SAIDA_PRODUTO_FK FOREIGN KEY (PRODUTO_id) REFERENCES PRODUTO(id)
);

CREATE TABLE LOTE(
	id INT AUTO_INCREMENT,
    dt_vencimento DATE,
    num_lote VARCHAR(20),
	qt_lote DECIMAL(9,3),
    LOTEcol VARCHAR(45),
    PRODUTO_id INT,
    PRIMARY KEY (id),
    CONSTRAINT LOTE_PRODUTO_FK FOREIGN KEY (PRODUTO_id) REFERENCES PRODUTO(id)
);

SHOW TABLES;

DESCRIBE CLIENTE;
DESCRIBE DOCUMENTO;
DESCRIBE ITEM_VENDA; 
DESCRIBE MUNICIPIO;
DESCRIBE PRODUTO;
DESCRIBE TIPO_PAGTO;
DESCRIBE UF;
DESCRIBE VENDA;
DESCRIBE TELEFONE;
DESCRIBE ENTRADA;
DESCRIBE SAIDA;
DESCRIBE LOTE;